custom:
  local-ip: 192.168.119.133
  win-ip: 192.168.0.110
spring:
  datasource:
    url: jdbc:mysql://${custom.local-ip}:3308/country_user?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: country-user
  redis:
    host: ${custom.local-ip}
    port: 6380
    database: 0
    password: root
  cloud:
    nacos:
      server-addr: ${custom.win-ip}:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kevin.user_service/pojo
server:
  port: 7000
# 用于生成jwt字符串
jwt:
  secretKey: kevin2
  tokenHead: 'Bearer '