spring:
  datasource:
    url: jdbc:mysql://192.168.119.132:3308/country_user?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: country_user
  redis:
    host: 192.168.119.132
    port: 6380
    database: 0
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kevin.user_service/pojo
server:
  port: 7000