server:
  port: 7020
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    name: country-mq
rocketmq:
  name-server: 192.168.0.110:9876
  producer:
    group: producerGroup1
    compress-message-body-threshold: 4096
    retry-next-server: true