custom:
  local-ip: 192.168.119.132
  win-ip: 192.168.0.110
spring:
  datasource:
    url: jdbc:mysql://${custom.local-ip}:3308/country_user?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: country-test
  redis:
    host: ${custom.local-ip}
    port: 6380
    database: 0
    password: root
  cloud:
    nacos:
      server-addr: ${custom.win-ip}:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kevin.test_service/pojo
server:
  port: 7001
# 用于生成jwt字符串
jwt:
  secretKey: kevin2
  tokenHead: 'Bearer '