custom:
  test-ip: 192.168.119.132
  test-port: 3308
  test-mycat-port: 8066
  win-ip: 192.168.0.110
spring:
  datasource:
    url: jdbc:mysql://${custom.test-ip}:${custom.test-mycat-port}/country_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: country-test
  redis:
    host: ${custom.test-ip}
    port: 6380
    database: 0
    password: root
  cloud:
    nacos:
      server-addr: ${custom.win-ip}:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.kevin.test_service/pojo
server:
  port: 7001
rocketmq:
  name-server: 192.168.0.110:9876
# 用于生成jwt字符串
jwt:
  secretKey: kevin2
  tokenHead: 'Bearer '



